[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory="netlify/functions"

[functions."sendEventReminder"]
  schedule = "0 * * * *"  # Runs at the top of every hour
